algoritmo " PositivoENegativo"
// Função :
// Autor :
// Data : 06/03/2023
// Seção de Declarações 
var
     numero: inteiro
inicio
   Escreva ("Escreva um número: ")
   Leia (numero)
   Se numero > 0 entao
      Se numero %2 = 0 entao
         Escreva ("Esse número é par")
      Senao
           Escreva ("Esse número é impar")
      FimSe
   Senao
        Se numero <0 entao
           Escreva ("Esse número não é positivo")
        FimSe
   FimSe


fimalgoritmo
