algoritmo "ÁreaCubo"
// Função :
// Autor :
// Data : 02/03/2023
// Seção de Declarações 
var
   a, b, c, aresta, area: real
inicio
      Escreval ("Escreva o valor do lado A: ")
      Leia (A)
      Escreval ("Escreva o valor do lado B: ")
      Leia (b)
      Escreval ("Escreva o valor do lado C: ")
      Leia (c)
      aresta <- (c^2)
      area <- (6* aresta)
      Escreva ("A Área do cubo é: ", area)
fimalgoritmo
