algoritmo "Financiamento"
// Função :
// Autor :
// Data : 06/03/2023
// Seção de Declarações 
var
   salario, financiamento: real
inicio
      Escreva ("Salário: ")
      Leia (salario)
      Escreva ("Valor do financiamento pretendido: ")
      Leia (financiamento)
      Se (financiamento <= 5* salario) entao
         Escreval ("Financiamento Concedido")
      Senao
           Escreval ("Financiamento Negado")
      FimSe
      Escreva ("Obrigado por nos consultar")
      
fimalgoritmo
