algoritmo "ContadorComPara"
// Função :
// Autor :
// Data : 06/03/2023
// Seção de Declarações 
var
     contador: inteiro
inicio
      Para contador  <- 1 ate 10 passo 1 faca
           Escreval (contador)
      FimPara

//contador com estrutura de repetição PARA
// sendo "passo 1" opcional, já que ele contaria de 1 em 1, caso queira dar um salto de 2 em 2, basta mudar o passo de 1 para 2.
fimalgoritmo
