algoritmo "CorrigindoProvas"
// Função :
// Autor :
// Data : 17/03/2023
// Seção de Declarações 
var
   c: inteiro
   gab: vetor [1..5]de caractere
inicio
      Escreval ("------------------------------")
      Escreval ("Passo 1- Cadastro de gabarito")
      Escreval ("------------------------------")
      para c de 1 ate 5 faca
           Escreva ("Questão ", c, ":")
           Leia (gab[c])
      FimPara
      LimpaTela
fimalgoritmo
