algoritmo "SomaFuncao"
// Função :
// Autor :
// Data : 16/03/2023
// Seção de Declarações 
var
   valor1, valor2, s: inteiro
   
Funcao soma (a, b: inteiro): inteiro
Inicio
      retorne a+b
FimFuncao

inicio
      Escreva ("Digite o primeiro valor: ")
      leia (valor1)
      Escreval ("Digite o segundo valor: ")
      leia (valor2)
      s <- soma (valor1, valor2)
      Escreva ("a soma entre ", valor1, " e ", valor2, " é ", s)
fimalgoritmo
